version: '3.4'

services:
  slackbottranslate:
    image: slackbottranslate
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
        SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
        SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/usr/src/app
    links: 
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - data:/data/db

volumes:
  data:
